services:
  go-dev:
    build: .
    container_name: container-name-1
    hostname: hostname-1
    user: devuser
    volumes:
      - type: bind
        source: ./app
        target: /app    
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "8080:8080"
    environment:
      - TERM=xterm-256color
