openapi: 3.0.0
info:
  title: Thing API
  description: A description about the application.
  version: 0.0.1

servers:
  - url: http://localhost:1111
    description: Example app for demonstration locally.

paths:
  /things:
    post:
      tags:
        - things
      summary: Add a new thing
      description: Add a new thing
      operationId: addThing
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Things"
        required: true
      responses:
        "200":
          description: Status code indicating success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Things"
        "400":
          description: Invalid ID supplied
        "404":
          description: Thing not found
    put:
      tags:
        - things
      summary: Update an existing thing
      description: Update an existing thing by Id
      operationId: updateThing
      requestBody:
        description: Update an existent thing
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Thing"
        required: true
      responses:
        "200":
          description: Status code indicating success
        "400":
          description: Invalid ID supplied
        "404":
          description: Thing not found
  /things/{thingId}:
    get:
      tags:
        - things
      summary: Get a thing
      operationId: getThingById
      parameters:
        - name: thingId
          in: path
          description: ID of thing to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Things"
            application/xml:
              schema:
                $ref: "#/components/schemas/Things"
        "400":
          description: Invalid ID supplied
        "404":
          description: Thing not found
    delete:
      tags:
        - things
      summary: Delete a thing
      operationId: deleteThingById
      parameters:
        - name: thingId
          in: path
          description: ID of thing to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Thing not found
components:
  schemas:
    Things:
      required:
        - name
        - description
        - type
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 99
        name:
          type: string
          description: name of the thing
          example: A cell phone
        description:
          type: string
          description: description of the thing
          example: A piece of hardware capable of communication remotely
        type:
          type: string
          description: type of thing (abstract or concrete)
          enum:
            - abstract
            - concrete
          example: concrete
